name: movies
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  cupertino_icons: ^1.0.8
  carousel_slider:
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  provider: ^6.1.5
  page_transition: ^2.2.1
  animated_toggle_switch: ^0.8.5
  injectable:
  get_it:
  http: ^1.4.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^9.2.4
  flutter_bloc: ^9.1.1
  lottie: ^3.3.1
  flutter_svg: ^2.2.0
  url_launcher: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner:
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splashLogo.png"


  flutter_lints: ^5.0.0


flutter:
  generate: true


  uses-material-design: true

  assets:
    - assets/images/
